### ISSUE TITLE
Cannot login into OBL sandbox account

### ISSUE THREAD

**Issue by swsr-capco** [OpenBankingUK/OBL-ModelBank-Integration#3]
Hi 

I am new to this open banking and want to develop an API to query a customers bank transactions 

I cannot get past the mits/mits login page, the app shows "Server Error" any ideas how I can get past this.
![openbankingError](https://github.com/OpenBankingUK/OBL-ModelBank-Integration/assets/151830951/3904295c-4c83-487a-99d6-4741c4194a99)
Also do I need to register as a bank to get moving forward?

**Comment by evgheniim-ozone** [comment]
Hello @swsr-capco 
For any questions or issues related to the usage of the Model Bank, please open a ticket in the OBL Service Desk at https://directory.openbanking.org.uk/obieservicedesk/s/. 
Thanks.
